// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCldyj-fk31JZ9Mz92p85SvsqoQrYfbyeY',
    appId: '1:652015481574:web:2e506546714bad19144127',
    messagingSenderId: '652015481574',
    projectId: 'prabit-release',
    authDomain: 'prabit-release.firebaseapp.com',
    storageBucket: 'prabit-release.firebasestorage.app',
    measurementId: 'G-N9DP7GDCMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCwq-d7Phv7Y-Lgz38hb0GlDLGI5p1pHA',
    appId: '1:652015481574:android:927851ed55221479144127',
    messagingSenderId: '652015481574',
    projectId: 'prabit-release',
    storageBucket: 'prabit-release.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_7NkGH2Xzv8FHaJf_aekPYy2m1fRTiaI',
    appId: '1:652015481574:ios:f0554c37972e4aa6144127',
    messagingSenderId: '652015481574',
    projectId: 'prabit-release',
    storageBucket: 'prabit-release.firebasestorage.app',
    iosBundleId: 'com.mycompany.prabitdesign',
  );
}
